app: dino
nodes: 1
tasks_per_node: 4
tag: dino
data:
  dataset_type: MRIDataset
  datasets: 
  - src/datasets/oasis3_all_bet.csv
  - src/datasets/ppmi_all_bet_nii_with_bbox.csv 
  - src/datasets/brats24_all_nii.csv
  - src/datasets/ixi_all_bet_nii_with_bbox.csv
  - src/datasets/mood_all_nii_with_bbox.csv
  - src/datasets/adni_all_bet_train.csv
  decode_one_clip: true  # unused
  batch_size: 8
  num_clips: 1
  num_frames: 128
  tubelet_size: 8
  sampling_rate: 1
  crop_size: 128
  patch_size: 8
  in_channel_size: 1
  random_clip_sampling: false
  pin_mem: true
  num_workers: 8
  filter_short_videos: false
  clip_duration: null
data_aug:
  auto_augment: true
  num_global_views: 2
  num_local_views: 4 #6
  random_noise: 0.1
  random_bias: 0.2
  intensity_gamma: 0.3
  max_offset_fraction: 0.1
  local_crop_ratio: 0.5
  random_resize_aspect_ratio:
  - 0.5 
  - 1.0 
  random_resize_scale:
  - 0.5
  - 1.0
  random_blur:
  - 0.5
  - 1.5
  rotation_degree: 20
  reprob: 0.0
logging:
  folder:  /gpfs/data/sodicksonlab/gozde/logs/ #/your_absolute_file_path_for_saving_logs_and_checkpoints/
  write_tag: dino
loss:
  loss_exp: 1.0 #2.0
  reg_coeff: 0.25
  temperature_student: 0.1
  temperature_teacher: 0.07
  momentum: 0.9
meta:
  load_checkpoint: false
  read_checkpoint: null # vitl16.pth.tar # null #r_file
  ckpt_folder: /gpfs/data/sodicksonlab/gozde/pretrained_weights/ # currently hardcoded in train!
  seed: 234 #1881 #234
  eval_freq: 100
  use_sdpa: true
  dtype: bfloat16
model:
  model_name: vit_base
  embed_dim: 768
  uniform_power: true # positional_embedding related, check later
optimization:
  ipe: null #300
  clip_grad: 1.0
  weight_decay: 0.005 #0.05
  final_weight_decay: 0.001 #0.1 #for large dataset
  epochs: 750
  warmup: 5
  start_lr: 2.0e-4 #5e-05
  lr: 3.0e-4 #1.0e-4
  final_lr: 5.0e-5 #1.0e-6
  drop_rate: 0.1 #0.1 #default
  attn_drop_rate: 0.1 #0.1 #default
  ema:
  - 0.996
  - 0.99
  grad_accum_steps: 2 #4
  betas:
  - 0.9
  - 0.95
