write_tag: tsne
nodes: 1
tasks_per_node: 1 #2
tag: mri-probe #k400-16x8x3
eval_name: mri_tsne_frozen
max_samples: 100
resume_checkpoint: false
checkpoint_path: null #/gpfs/data/sodicksonlab/gozde/logs/mjepa_eval_distributed_2024_12_03__11_16_35/model_ckpt/latest-model/jepa-latest.pth.tar # null #classification model
logging:
  folder: /gpfs/data/sodicksonlab/gozde/logs/
data:
  dataset_train:
  - src/datasets/adni_all_2class_bet_valtrain_oversampled.csv 
  dataset_val: 
  - src/datasets/adni_all_2class_bet_valtest.csv
  root_path: /gpfs/home/unalg01/jepa 
  dataset_type: MRIDataset
  num_classes: 2
  frames_per_clip: 144 #160 #128
  num_segments: 1
  num_views_per_segment: 1
  frame_step: 1
  num_workers: 0 #8
  random_clip_sampling: false
optimization:
  attend_across_segments: true
  num_epochs: 400
  resolution: 160 #128
  batch_size: 16
  weight_decay: 1.0e-3
  final_weight_decay: 1.0e-4 #0.1
  start_lr: 1.0e-5 #1.0e-5
  lr: 1.0e-4 #1.0e-5
  final_lr: 1.0e-6 #1.0e-6 
  warmup: 2
  use_bfloat16: true
  clip_grad_classifier: 10.0
  seed: 1881 #234
  train_log_iter_freq: 1
  val_log_iter_freq: 1
  layer_decay: 0.6 #0.75 #null to turn it off
  classifier_depth: 1
  dropout: 0.1 #0.25 #null to turn off
  drop_rate: 0.1
  attn_drop_rate: 0.1
pretrain:
  model_name: vit_base
  checkpoint_key: encoder #target_encoder
  clip_duration: null
  frames_per_clip: 144 #160 #128
  tubelet_size: 8
  uniform_power: true
  use_silu: false
  tight_silu: false
  use_sdpa: true
  patch_size: 8
  frozen: true
  clip_grad_encoder: 1.0
  encoder_warmup: 0
  use_pos_embed: false #true
  in_channel_size: 1
  frame_step: 1 # added
  folder: /gpfs/data/sodicksonlab/gozde/logs/mae_pretrain_distributed_2025_03_19__16_19_49/model_ckpt/latest-model/
  #/gpfs/data/sodicksonlab/gozde/logs/mjepa_pretrain_distributed_2025_04_06__15_20_50/model_ckpt/latest-model/
  #/gpfs/data/sodicksonlab/gozde/logs/dino_pretrain_distributed_2025_04_09__11_00_13/model_ckpt/latest-model/
  checkpoint: mae-latest.pth.tar #jepa-latest.pth.tar # name of pretrained encoder model file inside folder
