nodes: 1
tasks_per_node: 2
tag: mri-probe #k400-16x8x3
eval_name: video_classification_frozen
resume_checkpoint: false #true 
checkpoint_path: null #/gpfs/data/sodicksonlab/gozde/logs/mjepa_eval_distributed_2024_12_03__11_16_35/model_ckpt/latest-model/jepa-latest.pth.tar # null #classification model
logging:
  folder: /gpfs/data/sodicksonlab/gozde/logs/
data:
  root_path: /gpfs/home/unalg01/jepa
  dataset_train: src/datasets/adni_all_valtrain_split.csv
  dataset_val: src/datasets/adni_all_valtest_split.csv
  dataset_type: MRIDataset
  num_classes: 3
  frames_per_clip: 16
  num_segments: 16 # 4
  num_views_per_segment: 3
  frame_step: 1
  num_workers: 2
  random_clip_sampling: false
  auto_augment: true
optimization:
  attend_across_segments: true
  num_epochs: 400
  resolution: 224
  batch_size: 8
  weight_decay: 0.01
  lr: 0.0001
  start_lr: 0.0001
  final_lr: 0.0
  warmup: 0.
  use_bfloat16: true
  train_log_iter_freq: 1
  val_log_iter_freq: 10
pretrain:
  model_name: vit_base
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 16
  tubelet_size: 8
  uniform_power: true
  use_silu: false
  tight_silu: false
  use_sdpa: true
  patch_size: 8
  frozen: false #default: true
  clip_grad_encoder: 1.0
  encoder_warmup: 2
  in_channel_size: 1
  frame_step: 1 # added
  folder: /gpfs/data/sodicksonlab/gozde/logs/mjepa_pretrain_distributed_2025_01_19__18_15_33/model_ckpt/latest-model/
  #/your_absolute_file_path_to_directory_where_pretrained_models_are_contained/
  checkpoint: jepa-latest.pth.tar  # name of pretrained encoder model file inside folder
  write_tag: jepa
