nodes: 2
tasks_per_node: 4
tag: mri-probe #k400-16x8x3
eval_name: video_classification_frozen
resume_checkpoint: false #true 
checkpoint_path: null #/gpfs/data/sodicksonlab/gozde/logs/mjepa_eval_distributed_2024_12_03__11_16_35/model_ckpt/latest-model/jepa-latest.pth.tar # null #classification model
logging:
  folder: /gpfs/data/sodicksonlab/gozde/logs/
data:
  root_path: /gpfs/home/unalg01/jepa
  dataset_train: 
  - src/datasets/adni_all_3class_bet_train.csv 
  dataset_val: 
  - src/datasets/adni_all_3class_bet_val.csv 
  dataset_type: MRIDataset
  num_classes: 3
  frames_per_clip: 128
  num_segments: 1 #8 #for larger cropsize #rename to num_clips
  num_views_per_segment: 1
  frame_step: 1
  num_workers: 4
  random_clip_sampling: true
data_aug:
  auto_augment: true
  random_noise: 0.01
  random_bias: 0.1
  intensity_gamma: 0.1
  random_resize_aspect_ratio:
  - 0.9 
  - 1.1 
  random_resize_scale:
  - 0.9
  - 1.0
  rotation_degree: 10  
optimization:
  attend_across_segments: true
  num_epochs: 400
  resolution: 160 #192
  batch_size: 16
  weight_decay: 1.0e-3
  final_weight_decay: 1.0e-4 #0.1
  lr: 1.0e-4 #5.0e-5 #1.0e-5
  start_lr: 1.0e-6 #5.0e-5 #1.0e-5
  final_lr: 1.0e-7 #1.0e-6 
  warmup: 10
  use_bfloat16: true
  clip_grad_classifier: 10.0
  seed: 1881 #234
  train_log_iter_freq: 1
  val_log_iter_freq: 1
  layer_decay: 0.75 #null to turn it off
  classifier_depth: 2
  dropout: 0.3 #0.25 #null to turn off
pretrain:
  model_name: vit_base
  checkpoint_key: encoder #target_encoder
  clip_duration: null
  frames_per_clip: 128
  tubelet_size: 8
  uniform_power: true
  use_silu: false
  tight_silu: false
  use_sdpa: true
  patch_size: 8
  frozen: false #default: true
  clip_grad_encoder: 10.0
  encoder_warmup: 0
  use_pos_embed: false #true
  in_channel_size: 1
  frame_step: 1 # added
  folder: /gpfs/data/sodicksonlab/gozde/logs/mjepa_pretrain_distributed_2025_02_10__11_31_15/model_ckpt/periodic-model/
  # /gpfs/data/sodicksonlab/gozde/logs/mjepa_pretrain_distributed_2025_02_07__18_54_57/model_ckpt/periodic-model/
  # /gpfs/data/sodicksonlab/gozde/logs/mjepa_pretrain_distributed_2025_02_07__18_54_57/model_ckpt/latest-model/
  #/gpfs/data/sodicksonlab/gozde/logs/mjepa_pretrain_distributed_2025_02_04__14_18_36/model_ckpt/latest-model/
  # /gpfs/data/sodicksonlab/gozde/logs/mjepa_pretrain_distributed_2025_01_19__18_14_49/model_ckpt/latest-model/ #this path has to be given regardless of model filename
  # /gpfs/data/sodicksonlab/gozde/logs/mjepa_pretrain_distributed_2025_01_13__14_44_51/model_ckpt/latest-model/
  # /gpfs/data/sodicksonlab/gozde/logs/mjepa_pretrain_distributed_2025_01_14__21_08_18/model_ckpt/latest-model/ #corrupt model weights
  #/your_absolute_file_path_to_directory_where_pretrained_models_are_contained/
  checkpoint: jepa-periodic-epoch-201.pth.tar #jepa-periodic-epoch-501.pth.tar #jepa-latest.pth.tar  # name of pretrained encoder model file inside folder
  write_tag: jepa