nodes: 1
tasks_per_node: 4 #8
tag: mri-probe  #k400-16x8x3
eval_name: video_classification_frozen
resume_checkpoint: false
checkpoint_path: null
logging:
  folder: /gpfs/data/sodicksonlab/gozde/logs/
data:
  root_path: /gpfs/home/unalg01/jepa
  dataset_train: src/datasets/updated_nii_file_paths.csv
  dataset_val: src/datasets/updated_nii_file_paths.csv
  dataset_type: MRIDataset
  num_classes: 2
  frames_per_clip: 16
  num_segments: 16
  num_views_per_segment: 3
  frame_step: 1
  num_workers: 1
  random_clip_sampling: false
optimization:
  attend_across_segments: true
  num_epochs: 100 #20
  resolution: 224
  batch_size: 4
  weight_decay: 0.01
  lr: 0.001
  start_lr: 0.001
  final_lr: 0.000001
  warmup: 0.
  use_bfloat16: true
  train_log_iter_freq: 1
  val_log_iter_freq: 10
pretrain:
  model_name: vit_huge
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  use_silu: false
  tight_silu: false
  use_sdpa: true
  patch_size: 16
  frame_step: 1
  in_channel_size: 3
  folder: /gpfs/data/sodicksonlab/gozde/logs/mjepa_pretrain_distributed_2024_11_19__06_51_45/model_ckpt/best-model/  #/your_absolute_file_path_to_directory_where_pretrained_models_are_contained/
  checkpoint: jepa-best.pth.tar  # name of pretrained model file inside folder
  write_tag: jepa
