nodes: 1
tasks_per_node: 4
tag: mri-probe #k400-16x8x3
eval_name: video_classification_frozen
resume_checkpoint: true
checkpoint_path: logs/mjepa_eval_2024_11_30__23_14_12/model_ckpt/latest-model/jepa-latest.pth.tar #/home/gozde/medChangeDet/jepa/src/models/pretrained_weights/k400-probe.pth.tar #classification model
logging:
  folder: logs/
data:
  root_path: /home/gozde/medChangeDet/jepa/
  dataset_train: src/datasets/updated_nii_file_paths.csv
  dataset_val: src/datasets/updated_nii_file_paths.csv
  dataset_type: MRIDataset
  num_classes: 2
  frames_per_clip: 16
  num_segments: 16
  num_views_per_segment: 3
  frame_step: 1
optimization:
  attend_across_segments: true
  num_epochs: 200
  resolution: 224
  batch_size: 4 #4
  weight_decay: 0.01
  lr: 0.001
  start_lr: 0.001
  final_lr: 0.0
  warmup: 0.
  use_bfloat16: true
  train_log_iter_freq: 1
  val_log_iter_freq: 10
pretrain:
  model_name: vit_small
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  use_silu: false
  tight_silu: false
  use_sdpa: true
  patch_size: 16
  in_channel_size: 1
  frame_step: 1 # added
  folder: logs/mjepa_pretrain_2024_11_30__05_06_48/model_ckpt/latest-model/
  #/home/gozde/medChangeDet/jepa/logs/mjepa_pretrain_2024_11_10__18_48_47/model_ckpt/
  #/your_absolute_file_path_to_directory_where_pretrained_models_are_contained/
  checkpoint: jepa-latest.pth.tar #jepa-latest.pth.tar  # name of pretrained encoder model file inside folder
  write_tag: jepa
