app: mae
nodes: 1
tasks_per_node: 1  #1
tag: mae
data:
  dataset_type: MRIDataset
  datasets: # Relative path instead of abs path
  #- src/datasets/debug_nii_list_scan.csv
  # - src/datasets/scan_pretraining.csv
  #- src/datasets/debug_nii_list1024.csv
  - src/datasets/debug_nii_list64.csv
  #- src/datasets/debug_nii_list1.csv
  # - src/datasets/oasis3_all_bet.csv
  # - src/datasets/ppmi_all_bet_nii_with_bbox.csv 
  # - src/datasets/brats24_all_nii.csv
  # - src/datasets/ixi_all_bet_nii_with_bbox.csv
  # - src/datasets/mood_all_nii_with_bbox.csv
  # - src/datasets/adni_cv_folds_stratified/adni_pretrain.csv #- src/datasets/adni_all_bet_train.csv
  decode_one_clip: true  # unused
  batch_size: 1 #10 #16
  num_clips: 1 #8
  num_frames: 144 #128 #144 #160 #16
  tubelet_size: 8
  sampling_rate: 1
  crop_size: 144 #128 #160 #192 #224
  patch_size: 8
  in_channel_size: 1
  random_clip_sampling: false
  pin_mem: true
  num_workers: 0 #4
  filter_short_videos: false
  clip_duration: null
data_aug:
  auto_augment: true
  random_noise: 0.01
  random_bias: 0.1
  intensity_gamma: 0.1
  random_resize_aspect_ratio:
  - 0.9 
  - 1.1 
  random_resize_scale:
  - 0.9
  - 1.0
  rotation_degree: 10
  threshold_isotropy: 1.4
logging:
  folder:  /gpfs/data/sodicksonlab/gozde/logs/ #/your_absolute_file_path_for_saving_logs_and_checkpoints/
  write_tag: mae
loss:
  loss_exp: 2.0 #1.0
  reg_coeff: 0.0
  spectral_coeff: 2.0
  spec_loss_every_n_iter: 2
  min_epoch_for_spectral: 0
  high_pass_flag: true #false
  cutoff_ratio: 0.5 # used if high_pass_flag is on
mask:
  - aspect_ratio:
      - 1.0
      - 1.0
    num_blocks: 0.75
    spatial_scale:
      - 1
      - 1
    temporal_scale:
      - 1
      - 1
    max_temporal_keep: 1.0
    max_keep: null
meta:
  load_checkpoint: false #true 
  read_checkpoint: null #mae-latest.pth.tar # vitl16.pth.tar 
  ckpt_folder: /gpfs/data/sodicksonlab/gozde/logs/mae_pretrain_distributed_2025_06_03__12_24_04/model_ckpt/latest-model/
  #/gpfs/data/sodicksonlab/gozde/logs/mae_pretrain_distributed_2025_03_19__16_19_49/model_ckpt/latest-model/
  #/gpfs/data/sodicksonlab/gozde/logs/mae_pretrain_distributed_2025_03_06__15_13_47/model_ckpt/latest-model/
  # /gpfs/data/sodicksonlab/gozde/logs/mae_pretrain_distributed_2025_03_06__16_12_23/model_ckpt/latest-model/ 
  #/gpfs/data/sodicksonlab/gozde/logs/mae_pretrain_distributed_2025_03_06__15_13_15/model_ckpt/latest-model/
  seed: 1881 #234
  eval_freq: 100
  use_sdpa: true
  dtype: bfloat16
model:
  model_name: vit_base #vit_small_mod  
  pred_model_name:  vit_decoder #vit_decoder_mod
  pred_depth: 12 #8
  pred_embed_dim: 768 #384
  uniform_power: true # positional_embedding related, check later
  use_mask_tokens: true
  zero_init_mask_tokens: true #false
optimization:
  ipe: null
  clip_grad: 1.0
  weight_decay: 0.005
  final_weight_decay: 0.001 #0.1 #for large dataset
  epochs: 200
  warmup: 0
  start_lr: 1.0e-4 #1.0e-4 #3.0e-5 #5e-05
  lr: 5.0e-4 #1.0e-3 #2.0e-4 #1.0e-4
  final_lr: 1.0e-6 #1.0e-5 #5.0e-6 #1.0e-6
  drop_rate: 0.0 #0.1 #default
  attn_drop_rate: 0.0 #0.1 #default
  grad_accum_steps: 2 #4
  betas:
  - 0.9
  - 0.975