app: mae
nodes: 1
tasks_per_node: 4  #1
tag: mae
data:
  dataset_type: MRIDataset
  datasets: # Relative path instead of abs path
  - src/datasets/oasis3_all_bet_nii_with_bbox.csv
  - src/datasets/ppmi_all_bet_nii_with_bbox.csv 
  - src/datasets/brats24_all_nii.csv
  - src/datasets/ixi_all_bet_nii_with_bbox.csv
  - src/datasets/mood_all_nii_with_bbox.csv
  - src/datasets/adni_all_bet_train.csv
  decode_one_clip: true  # unused
  batch_size: 64 #32
  num_clips: 1 #8
  num_frames: 192 #16
  tubelet_size: 16 #8
  sampling_rate: 1
  crop_size: 192 #128 #160 #192 #224
  patch_size: 16 #8
  in_channel_size: 1
  random_clip_sampling: false
  pin_mem: true
  num_workers: 8 #8 #12
  filter_short_videos: false
  clip_duration: null
data_aug:
  auto_augment: true
  random_noise: 0.01
  random_bias: 0.1
  intensity_gamma: 0.1
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.9 
  - 1.1 
  random_resize_scale:
  - 0.9
  - 1.0
  rotation_degree: 10
  reprob: 0.0
logging:
  folder:  /gpfs/data/sodicksonlab/gozde/logs/ #/your_absolute_file_path_for_saving_logs_and_checkpoints/
  write_tag: mae
loss:
  loss_exp: 2.0 #1.0
  reg_coeff: 0.0
mask:
  - aspect_ratio:
      - 1.0
      - 1.0
    num_blocks: 0.7
    spatial_scale:
      - 1
      - 1
    temporal_scale:
      - 1
      - 1
    max_temporal_keep: 1.0
    max_keep: null
meta:
  load_checkpoint: false
  read_checkpoint: null # vitl16.pth.tar # null #r_file
  ckpt_folder: /gpfs/data/sodicksonlab/gozde/pretrained_weights/ # currently hardcoded in train!
  seed: 1881 #234
  eval_freq: 100
  use_sdpa: true
  dtype: bfloat16
model:
  model_name: vit_base
  pred_depth: 12 #8
  pred_embed_dim: 768
  uniform_power: true # positional_embedding related, check later
  use_mask_tokens: true
  zero_init_mask_tokens: false #true
optimization:
  ipe: null #300
  ipe_scale: 1.25
  clip_grad: 1.0
  weight_decay: 0.005
  final_weight_decay: 0.001 #0.1 #for large dataset
  epochs: 500
  warmup: 20
  start_lr: 3.0e-5 #3e-05
  lr: 2.0e-4 #1.0e-4
  final_lr: 5.0e-6 #1.0e-6
